### ISSUE TITLE
[bug] redirecting fail

### ISSUE THREAD

**Issue by zzz6519003** [octo-linker/chrome-extension#57]
https://github.com/facebook/react/blob/35962a00084382b49d1f9e3bd36612925f360e5b/src/renderers/shared/reconciler/ReactCompositeComponent.js#L15
:+1:

**Comment by stefanbuck** [comment]
I don't think this is a bug, because if the module would be available on npm it would work. The react project is using the CommonJS style for dependency management but without publish the modules on npm. They are using https://www.npmjs.com/package/commoner for that, if you are interested. 

This is a common problem for the octo-linker. I've noticed the same behaviour for https://github.com/atom/electron packages like `require('BrowserWindow')`. I'm not sure how well this problem could be fixed. Maybe you have a clever idea how to solve it, without depending heavily on a project structure.

**Comment by zzz6519003** [comment]
:beer:
