### ISSUE TITLE
Incorrectly identifying Ruby files

### ISSUE THREAD

**Issue by timdorr** [octo-linker/chrome-extension#63]
Example: https://github.com/rails/rails/blob/master/load_paths.rb

The `require 'bundler'` line is being linked to an NPM package that doesn't exist. Happens with any .rb file I've tried. 

I've looked through the code a bit, but I'm not sure of the cause offhand. I believe there's some stuff to limit linking to certain file and code block types. Is that not working because of a Github change?

**Comment by stefanbuck** [comment]
Hi @timdorr, thanks for reporting this behaviour. I'm already aware of this behaviour. The current implementation covers only JavaScript and manifest files for `package.json`, `bower.json` and `composer.json`. The linke replacement is super fuzzy, that's the reason why I started a couple of months ago a complete rewrite (see [dev branch](https://github.com/octo-linker/chrome-extension/tree/dev)). Unfortunately I'm struggling with the completion, because of lack of time. But soon as the ground work is in place, it will be super easy to add support for other languages (fingers crossed) :wink:  

Are you interested in contributing? I'm looking for help especially for https://github.com/octo-linker/live-resolver/issues/5

**Comment by stefanbuck** [comment]
I close this, because it's already on the todo list https://github.com/octo-linker/chrome-extension/issues/43 :wink:
